# Generated by Django 6.0.4 on 2026-05-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopiedFile',
            fields=[
                ('blake3', models.TextField(primary_key=True, serialize=False, verbose_name='BLAKE3')),
                ('path', models.TextField(verbose_name='Path')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Скопированный файл',
                'verbose_name_plural': 'Скопированные файлы',
            },
        ),
    ]
