# Generated by Django 6.0.4 on 2026-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='Path')),
                ('size', models.PositiveBigIntegerField(verbose_name='Size')),
                ('file_type', models.TextField(verbose_name='File type')),
                ('mtime', models.DateTimeField(verbose_name='mtime')),
                ('blake3', models.TextField(verbose_name='BLAKE3')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
            },
        ),
    ]
