# Generated by Django 6.0.4 on 2026-05-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='mtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='mtime'),
        ),
    ]
